changelog:
  exclude:
    labels:
      - dependencies
      - skip-changelog
  categories:
    - title: Highlights
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - maintenance
    - title: Other changes
      labels:
        - "*"
