import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from agentic_rl_forge.cli import app
from agentic_rl_forge.contracts import AuditSeverity
from agentic_rl_forge.quality import ReleaseAuditor


def make_release_fixture(root: Path) -> None:
    (root / ".github/workflows").mkdir(parents=True)
    (root / "docs").mkdir()
    (root / "README.md").write_text(
        "# Ready Project\n\nSee [guide](docs/guide.md).\n",
        encoding="utf-8",
    )
    (root / "CHANGELOG.md").write_text("# Changelog\n", encoding="utf-8")
    (root / "docs/guide.md").write_text("# Guide\n", encoding="utf-8")
    (root / "LICENSE").write_text(
        "Apache License\nVersion 2.0, January 2004\n",
        encoding="utf-8",
    )
    (root / "SECURITY.md").write_text("# Security\n", encoding="utf-8")
    (root / "CONTRIBUTING.md").write_text("# Contributing\n", encoding="utf-8")
    (root / ".github/workflows/ci.yml").write_text("name: CI\n", encoding="utf-8")
    (root / ".github/workflows/release.yml").write_text(
        "name: Release\n",
        encoding="utf-8",
    )
    (root / "pyproject.toml").write_text(
        """
[project]
name = "ready-project"
version = "0.1.0"
description = "Release audit fixture"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "Apache-2.0" }
""".strip()
        + "\n",
        encoding="utf-8",
    )


def test_release_audit_can_pass_without_strict_git(tmp_path: Path) -> None:
    make_release_fixture(tmp_path)

    report = ReleaseAuditor(tmp_path).run(strict_git=False)

    assert report.ready
    assert report.error_count == 0
    assert any(item.code == "git.repository" for item in report.findings)
    assert all(item.severity is not AuditSeverity.ERROR for item in report.findings)


def test_release_audit_detects_secrets_and_broken_links(tmp_path: Path) -> None:
    make_release_fixture(tmp_path)
    (tmp_path / "README.md").write_text(
        "# Project\n\n[missing](docs/missing.md)\n",
        encoding="utf-8",
    )
    secret = "AKIA" + "A" * 16
    generation_trace = "Generated by " + "Chat" + "GPT"
    (tmp_path / "config.txt").write_text(
        secret + "\n" + generation_trace + "\n",
        encoding="utf-8",
    )

    report = ReleaseAuditor(tmp_path).run(strict_git=False)
    errors = {item.code for item in report.findings if item.severity is AuditSeverity.ERROR}

    assert not report.ready
    assert "docs.local-links" in errors
    assert "security.secrets" in errors
    assert "provenance.generation-traces" in errors


def test_release_audit_skips_temp_directories_and_unreadable_files(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    make_release_fixture(tmp_path)
    browser_profile = tmp_path / ".tmp-browser" / "profile"
    browser_profile.mkdir(parents=True)
    (browser_profile / "lockfile").write_text("AKIA" + "A" * 16, encoding="utf-8")
    unreadable = tmp_path / "locked.txt"
    unreadable.write_text("local runtime state", encoding="utf-8")
    original_read_text = Path.read_text

    def guarded_read_text(path: Path, *args: object, **kwargs: object) -> str:
        if path == unreadable:
            raise PermissionError("file is locked by another process")
        return original_read_text(path, *args, **kwargs)

    monkeypatch.setattr(Path, "read_text", guarded_read_text)

    report = ReleaseAuditor(tmp_path).run(strict_git=False)

    assert report.ready
    assert not any(
        item.code == "security.secrets" and item.severity is AuditSeverity.ERROR
        for item in report.findings
    )


def test_strict_release_audit_requires_git_history(tmp_path: Path) -> None:
    make_release_fixture(tmp_path)
    (tmp_path / ".git").mkdir()

    report = ReleaseAuditor(tmp_path).run()
    error_codes = {
        finding.code for finding in report.findings if finding.severity is AuditSeverity.ERROR
    }

    assert not report.ready
    assert "git.initial-commit" in error_codes


def test_current_repository_audit_has_no_documentation_placeholders(tmp_path: Path) -> None:
    project = Path(__file__).resolve().parents[1]
    output = tmp_path / "release-audit.json"
    runner = CliRunner()

    result = runner.invoke(
        app,
        ["release-audit", "--project", str(project), "--output", str(output)],
    )
    payload = json.loads(output.read_text(encoding="utf-8"))
    error_codes = {
        finding["code"] for finding in payload["findings"] if finding["severity"] == "error"
    }

    assert result.exit_code == (0 if payload["ready"] else 1)
    assert "docs.placeholders" not in error_codes
    assert "security.secrets" not in error_codes
    assert "provenance.generation-traces" not in error_codes
